GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJUYXJyaSBQZXdlIiwiZW1haWwiOiJ0YXJyaXBld2VAZ21haWwuY29tIiwiaWF0IjoxNjgxMTc2MTA0LCJleHAiOjE2ODExNzk3MDR9.NeuBJZ8OdPrNQ6cWSJlCA3VCO0PbPmHGphMyA26aIRw

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"Tarri Pewe 2",
    "email":"tarripewe3@gmail.com",
    "password":"12345678",
    "confirmPassword":"12345678"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"tarripewe@gmail.com",
    "password":"12345678"
}

###
GET http://localhost:3000/token

###
DELETE http://localhost:3000/logout